#!/usr/bin/perl 

use NethServer::SSSD;
my $sssd = new NethServer::SSSD();

if ($sssd->isLdap()) {
    system('/usr/bin/mysql dolibarr < /usr/share/dolibarr/htdocs/install/userLdap.sql');
    system('/usr/bin/scl enable rh-php73 -- /usr/share/dolibarr//scripts/user/sync_users_ldap2dolibarr.php commitiferror --server=localhost -y > /dev/null');
}

# overwrite dolibarr configuration 
system('/usr/sbin/e-smith/expand-template /usr/share/dolibarr/htdocs/conf/conf.php');
