#!/usr/bin/perl


use strict;
use warnings;
use NethServer::Password;
use esmith::ConfigDB;

my $db = esmith::ConfigDB->open() || die("Can't open db");


my $old_version = $db->get_prop('dolibarr','rpmVersion') || '11.0.3';
$old_version =~ s/\.//g;

my $version = `/usr/bin/rpm -qi nethserver-dolibarr | awk -F': ' '/Version/ {print \$2}'`;
$version =~ s/\.//g;
chomp $version;

##test if the mysql db is created, if not then the user and the mysql db are created
if ( ! -d '/var/lib/mysql/dolibarr') {
    my $password = NethServer::Password::store('dolibarr') || die('Could not generate dolibarr password!');

    my $commands = join("\n", 
    	      "GRANT ALL PRIVILEGES ON `dolibarr`.* TO 'dolibarr'\@'localhost' IDENTIFIED BY '$password';",
    	      "FLUSH PRIVILEGES;",
    	      "CREATE DATABASE IF NOT EXISTS dolibarr DEFAULT CHARACTER SET = 'utf8';"
         ) . "\n";

    print $commands;

    open(FH, '|-', '/usr/bin/mysql -B -f') || die("[ERROR] Could not connect to mysql");
    print FH $commands;
    close(FH);

    unlink ('/usr/share/dolibarr/documents/install.lock');

    # Install with CURL
    print "#\n# Initial importation of the dolibarr mysql database\n#";
    system('curl -kL -H "Host: 127.0.0.1" -X POST https://127.0.0.1/dolibarr/install/fileconf.php > /dev/null 2>&1'); 
    system('curl -kL -H "Host: 127.0.0.1" -X POST https://127.0.0.1/dolibarr/install/step1.php --data "testpost=ok&action=set&selectlang=en_US" > /dev/null 2>&1');
    system('curl -kL -H "Host: 127.0.0.1" -X POST https://127.0.0.1/dolibarr/install/step2.php --data "testpost=ok&action=set&selectlang=en_US" > /dev/null 2>&1');
    system('curl -kL -H "Host: 127.0.0.1" -X POST https://127.0.0.1/dolibarr/install/step4.php --data "testpost=ok&action=set&selectlang=en_US" > /dev/null 2>&1');
    system('curl -kL -H "Host: 127.0.0.1" -X POST https://127.0.0.1/dolibarr/install/step5.php --data "testpost=ok&action=set&selectlang=en_US&pass=admin&pass_verif=admin" > /dev/null 2>&1');

    system('touch /usr/share/dolibarr/documents/install.lock');

    $version = `/usr/bin/rpm -qi nethserver-dolibarr | awk -F': ' '/Version/ {print \$2}'`;
    chomp $version;

    $db->set_prop('dolibarr','rpmVersion',$version);
    exit (0);

} elsif ($old_version < $version) {

    # backup , it is a spare wheel 
    mkdir '/var/lib/nethserver/backup_db_dolibarr';
    my ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime();
    $year = 1900 + $year;
    $mon = 1 + $mon;
    system("/usr/bin/mysqldump dolibarr > /var/lib/nethserver/backup_db_dolibarr/dolibar-$year-$mon-$mday-$hour-$min");
    system('/usr/bin/chmod -R 400 /var/lib/nethserver/backup_db_dolibarr/');

    # find version REAL VERSION
    $old_version = $db->get_prop('dolibarr','rpmVersion');
    $version = `/usr/bin/rpm -qi nethserver-dolibarr | awk -F': ' '/Version/ {print \$2}'`;
    chomp $version;
    # now dolibarr seems to make mysql database fixes between major version eg 12->13
    # think to check https://192.168.12.183/dolibarr/install/index.php
    $version =~ /(\d+)/;
    my $indexversion = $1;
    $old_version =~ /(\d+)/;
    my $indexold_version = $1;

    print "upgrade from $old_version to  $version\n";
    system("/etc/e-smith/events/actions/nethserver-dolibarr-do-database-upgrade $indexold_version $indexversion");

    $db->set_prop('dolibarr','rpmVersion',$version);

} else {
    $version = `/usr/bin/rpm -qi nethserver-dolibarr | awk -F': ' '/Version/ {print \$2}'`;
    chomp $version;
    $db->set_prop('dolibarr','rpmVersion',$version);
}
