#!/bin/bash

#
# we use the internal php console to upgrade the mysql db
#
old_version=$1
version=$2
# allow to unlock 
/usr/bin/rm -f /usr/share/dolibarr/documents/install.lock
# we have some paths misconfiguration  (include ../folder)
cd /usr/share/dolibarr/htdocs/install/
# do upgrade
/opt/rh/rh-php73/root/bin/php /usr/share/dolibarr/htdocs/install/upgrade.php  $old_version $version  > /tmp/dolibarr_upgrade.php
/opt/rh/rh-php73/root/bin/php /usr/share/dolibarr/htdocs/install/upgrade2.php $old_version $version  > /tmp/dolibarr_upgrade2.php
/opt/rh/rh-php73/root/bin/php /usr/share/dolibarr/htdocs/install/step5.php    $old_version $version  > /tmp/dolibarr_step5.php

/usr/bin/touch /usr/share/dolibarr/documents/install.lock